name: Feature Request
description: Suggest a new feature or improvement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you'd like to see.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature
      placeholder: What should be built?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Checklist of conditions that must be met
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, references, related issues, etc.
    validations:
      required: false
