name: Task
description: Internal task, refactor, or chore
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the task to be done.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Definition of done
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Related issues, technical notes, etc.
    validations:
      required: false
